---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: k8s.clusters.platform.silvios.me
  labels:
    provider: kubernetes
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: platform.silvios.me/v1
    kind: Cluster
  resources:
    - name: kubernetes-configmap
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
          transforms:
            - type: string
              string:
                fmt: "cluster-%s"

        - type: FromCompositeFieldPath
          fromFieldPath: "spec.ingress.cname"
          toFieldPath: "spec.forProvider.manifest.data.cname"

        - type: FromCompositeFieldPath
          fromFieldPath: "spec.ingress.domain"
          toFieldPath: "spec.forProvider.manifest.data.domain"
