---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.database.silvios.me
spec:
  scope: Namespaced

  group: database.silvios.me

  names:
    plural: postgresqls
    singular: postgresql
    kind: PostgreSQL
    shortNames:
      - pgsql

  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
