kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rules-for-developers
  namespace: development
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rules-for-developers
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers-can-get-and-list-replicasets
  namespace: development
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developers-can-get-and-list-replicasets
  apiGroup: rbac.authorization.k8s.io
