kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: rules-for-developers
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "update", "list", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "update", "list", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: developers-can-get-and-list-replicasets
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list"]
