apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /home/${CSR_USER}/.kube/${CLUSTER_NAME}-ca.crt
    server: ${CLUSTER_ENDPOINT}
  name: ${CLUSTER_NAME}
users:
- name: ${CSR_USER}
  user:
    client-certificate-data: ${CLIENT_CERTIFICATE_DATA}
contexts:
- context:
    cluster: ${CLUSTER_NAME}
    user: ${CSR_USER}
  name: ${CSR_USER}-${CLUSTER_NAME}
current-context: ${CSR_USER}-${CLUSTER_NAME}
