apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositebuckets.storage.gcp.silvios.me
spec:
  group: storage.gcp.silvios.me
  names:
    kind: CompositeBucket
    plural: compositebuckets
  claimNames:
    kind: Bucket
    plural: buckets
    shortNames:
      - bk
      - bkts
  connectionSecretKeys:
    - name
    - url
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                    enum:
                     - USA
                     - Europe
                     - Brazil
                  prefix:
                    type: string
                    default: generic-bucket
                required:
                  - location
            required:
              - parameters
