apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
