---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - ${IP_SERVER}/24
      nameservers:
        search: [${DOMAIN_NAME}]
        addresses: [${IP_DNS}, 8.8.8.8, 8.8.4.4]
      routes:
      - to: 10.96.0.0/12
        via: ${IP_SERVER}
