apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mysupersecret
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: wasp-foundation

  target:
    name: secret-to-be-created
    creationPolicy: Owner

  data:
    - secretKey: mysupersecret
      remoteRef:
        key: secret/mysupersecret
