---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default

  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc

  source:
    path: charts/httpbin
    repoURL: https://github.com/smsilva/helm.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
