---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin1
  namespace: argocd
spec:
  destination:
    namespace: httpbin1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/httpbin
    repoURL: https://github.com/smsilva/helm.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin2
  namespace: argocd
spec:
  destination:
    namespace: httpbin2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/httpbin
    repoURL: https://github.com/smsilva/helm.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
