notifications:
  enabled: true

  logLevel: "debug"

  argocdUrl: https://localhost:32080

  subscriptions:
    - recipients:
        - googlechat:argocd-notifications-devops-team
        - telegram:silviosargocd
      triggers:
        - on-deployed
        - on-sync-succeeded

    - recipients:
        - googlechat:argocd-notifications-devops-team
      triggers:
        - on-health-degraded
        - on-sync-failed
        - on-sync-status-unknown

  notifiers:
    service.telegram: |
      token: $telegram-token

    service.googlechat: |
      webhooks:
        argocd-notifications-devops-team: $google-chat-webhook-url-devops-team

  templates:
    template.app-deployed: |
      message: |
        \[*{{.app.metadata.name}}*] *DEPLOYMENT* was *SUCCEEDED*.
        Revision: {{ .app.status.sync.revision }}
      googlechat:
        cards: |
          - header:
              title: ArgoCD Bot Notification
            sections:
              - widgets:
                  - textParagraph:
                      text: The app {{ .app.metadata.name }} has succesfully DEPLOYED.
              - widgets:
                  - keyValue:
                      topLabel: Repository
                      content: {{ call .repo.RepoURLToHTTPS .app.spec.source.repoURL }}
                  - keyValue:
                      topLabel: Revision
                      content: {{ .app.spec.source.targetRevision }}
                  - keyValue:
                      topLabel: Author
                      content: {{ (call .repo.GetCommitMetadata .app.status.sync.revision).Author }}

    template.app-sync-succeeded: |
      message: |
        \[*{{.app.metadata.name}}*] *SYNC* was *SUCCEEDED*.
      googlechat:
        cards: |
          - header:
              title: ArgoCD Bot Notification
            sections:
              - widgets:
                  - textParagraph:
                      text: The app {{ .app.metadata.name }} has succesfully SYNCED.
              - widgets:
                  - keyValue:
                      topLabel: Repository
                      content: {{ call .repo.RepoURLToHTTPS .app.spec.source.repoURL }}
                  - keyValue:
                      topLabel: Revision
                      content: {{ .app.spec.source.targetRevision }}
                  - keyValue:
                      topLabel: Author
                      content: {{ (call .repo.GetCommitMetadata .app.status.sync.revision).Author }}

    template.app-sync-failed: |
      message: |
        \[*{{.app.metadata.name}}*] *SYNC* was *FAILED*.

    template.app-sync-status-unknown: |
      message: |
        \[*{{.app.metadata.name}}*] *SYNC* was *UNKNOWN*.

    template.app-health-degraded: |
      message: |
        \[*{{.app.metadata.name}}*] *HEALTH* is *DEGRADED*.

  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
          - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'

    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
          - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']

    trigger.on-sync-failed: |
      - description: Application syncing has failed
        send:
          - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']

    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        send:
          - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'

    trigger.on-health-degraded: |
      - description: Application has degraded
        send:
          - app-health-degraded
        when: app.status.health.status == 'Degraded'
