# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: httpbin-ext
#   name: httpbin-ext
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: httpbin-ext
# subsets:
#   - addresses:
#       - ip: 17.17.17.17
#     ports:
#       - port: 80
