{{- range $cluster := .Values.clusters }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ $cluster.clusterSecretStore }}
spec:
  provider:
    azurekv:
      authType: ServicePrincipal

      tenantId: {{ $.Values.azurerm.tenantId }}
      vaultUrl: https://{{ $cluster.clusterSecretStore }}.vault.azure.net

      authSecretRef:
        clientId:
          key: ARM_CLIENT_ID
          name: azurerm-service-principal
          namespace: default

        clientSecret:
          key: ARM_CLIENT_SECRET
          name: azurerm-service-principal
          namespace: default
{{- end }}
