# Certificate Challenges failing with Istio + Istio Gateway when installed via Helm
# https://github.com/istio/istio/issues/37329

# Kubernetes Ingress not working
# https://github.com/istio/istio/issues/36444

# Default access log format
# https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format

# Envoy Access logging
# https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators

# Customizing Istio Metrics
# https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

# Stats Config (MetricConfig)
# https://istio.io/latest/docs/reference/config/proxy_extensions/stats/

# Prometheus Rate Example
# rate(istio_request_duration_milliseconds_sum{reporter="source",destination_workload="httpbin"}[1m])

meshConfig:
  ingressService: istio-ingress
  ingressSelector: ingress
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  accessLogFormat: |
    {
      "authority": "%REQ(:AUTHORITY)%",
      "bytes_received": "%BYTES_RECEIVED%",
      "bytes_sent": "%BYTES_SENT%",
      "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
      "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "duration": "%DURATION%",
      "host_name": "%HOSTNAME%",
      "method": "%REQ(:METHOD)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      "protocol": "%PROTOCOL%",
      "request_duration": "%REQUEST_DURATION%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "requested_server_name": "%REQUESTED_SERVER_NAME%",
      "response_code_details": "%RESPONSE_CODE_DETAILS%",
      "response_code": "%RESPONSE_CODE%",
      "response_flags": "%RESPONSE_FLAGS%",
      "route_name": "%ROUTE_NAME%",
      "start_time": "%START_TIME(%s.%9f)%",
      "upstream_cluster": "%UPSTREAM_CLUSTER%",
      "upstream_host": "%UPSTREAM_HOST%",
      "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
      "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
      "user_agent": "%REQ(USER-AGENT)%",
      "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
      "x_gateway": "%REQ(X-W1-GATEWAY)%",
      "x_wasp_id": "%REQ(X-WASP-ID)%"
    }

telemetry:
  enabled: true

  v2:
    enabled: true

    prometheus:
      enabled: true

      configOverride:
        gateway:
          metrics:
            - tags_to_remove:
                - connection_security_policy
                - destination_app
                - destination_canonical_revision
                - destination_canonical_service
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_service_namespace
                - destination_version
                - grpc_response_status
                - request_protocol
                - response_flags
                - security_istio_io_tlsMode
                - service_istio_io_canonical_name
                - service_istio_io_canonical_revision
                - source_app
                - source_canonical_revision
                - source_canonical_service
                - source_cluster
                - source_principal
                - source_version

        inboundSidecar:
          metrics:
            - tags_to_remove:
                - connection_security_policy
                - destination_app
                - destination_canonical_revision
                - destination_canonical_service
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_service_namespace
                - destination_version
                - grpc_response_status
                - request_protocol
                - response_flags
                - security_istio_io_tlsMode
                - service_istio_io_canonical_name
                - service_istio_io_canonical_revision
                - source_app
                - source_canonical_revision
                - source_canonical_service
                - source_cluster
                - source_principal
                - source_version

        outboundSidecar:
          metrics:
            - tags_to_remove:
                - connection_security_policy
                - destination_app
                - destination_canonical_revision
                - destination_canonical_service
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_service_namespace
                - destination_version
                - grpc_response_status
                - request_protocol
                - response_flags
                - security_istio_io_tlsMode
                - service_istio_io_canonical_name
                - service_istio_io_canonical_revision
                - source_app
                - source_canonical_revision
                - source_canonical_service
                - source_cluster
                - source_principal
                - source_version
