---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-cluster-events
spec:
  cooldownPeriod: 120

  scaleTargetRef:
    name: wasp-item-consumer

  triggers:
    - type: rabbitmq

      metadata:
        protocol: amqp
        queueName: cluster-events
        mode: QueueLength
        value: "10"
        metricName: custom-cluster-events

      authenticationRef:
        name: rabbitmq-authentication
