dns:
  prefix: silvios-dev
  domain: .eastus2.cloudapp.azure.com

issuer:
  name: letsencrypt
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  # server: https://acme-v02.api.letsencrypt.org/directory
  email: smsilva@gmail.com

istio:
  ingress:
    secret:
      name: istio-ingress-tls
