apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        env:
      {{- range $rabbit := .Values.rabbitmq }}
      {{- range $item := $rabbit.data }}
        - name: {{ $item.variableName }}
          valueFrom:
            configMapKeyRef:
              name: {{ $rabbit.name }}
              key: {{ $item.keyName }}
      {{- end }}
      {{- end }}
