---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
  namespace: istio-ingress
spec:
  secretName: ingress-tls
  
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging-istio
  
  commonName: ingress.8u6wl.sandbox.wasp.silvios.me
  
  dnsNames:
    - ingress.8u6wl.sandbox.wasp.silvios.me
