---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
  namespace: istio-ingress
spec:
  secretName: ingress-tls
  
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging-istio
  
  commonName: httpbin.7xb9x.sandbox.wasp.silvios.me
  
  dnsNames:
    - httpbin.7xb9x.sandbox.wasp.silvios.me

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-gateway
  namespace: istio-ingress
spec:
  secretName: ingress-tls-gateway
  
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging-istio
  
  commonName: gateway.7xb9x.sandbox.wasp.silvios.me
  
  dnsNames:
    - gateway.7xb9x.sandbox.wasp.silvios.me
