server:
  service:
    type: NodePort
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    namedTargetPort: true
    nodePortHttp: 32080
    nodePortHttps: 32443
