replicaCount: 1

image:
  repository: silviosilva/demo-redis
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []
nameOverride: "demo-redis"
fullnameOverride: "demo-redis"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: demo-redis.local
      paths: []
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

external:
  - name: redis-01
    port: 6379
    externalName: silvios-01.redis.cache.windows.net
  - name: redis-02
    port: 6379
    externalName: silvios-02.redis.cache.windows.net

env:
  - name: REDIS_HOSTNAME
    value: "redis-01.external.svc.cluster.local"
  - name: REDIS_HOSTPORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
