replicaCount: 1

image:
  repository: demo-redis
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []
nameOverride: "demo-redis"
fullnameOverride: "demo-redis"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: demo-redis.local
      paths: []
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

external:
  - name: redis-01-external
    port: 6379
    address: 10.0.0.124
  - name: redis-02-external
    port: 6380
    address: 10.0.0.124

env:
  - name: REDIS_HOSTNAME
    value: "redis-01-external.demo.svc.cluster.local"
  - name: REDIS_HOSTPORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: "GMyIurI2LqvSN/wKsklBUY0KYPUbfiv1maVc6OGhGIikH7Q/7PDlEeF1fZa0fydp+NK0MEuH0oS4mNqx"
  # - name: REDIS_HOSTNAME
  #   value: "my-release-redis-master.demo.svc.cluster.local"
  # - name: REDIS_HOSTPORT
  #   value: "6379"
  # - name: REDIS_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-release-redis
  #       key: redis-password

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
