remote_write:
  - url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server={{ .Values.global.cluster }}
    authorization:
      credentials_file: /etc/secrets/newrelic/license

    write_relabel_configs:
      - source_labels: [__name__]
        regex: "\
          apiserver_flowcontrol_current_inqueue_requests|\
          envoy_cluster_upstream_cx_rx_bytes_total|\
          envoy_cluster_upstream_rq|\
          etcd_db_total_size_in_bytes|\
          istio_request_bytes_sum|\
          istio_request_duration_milliseconds(.*)|\
          istio_requests_total(.*)|\
          istio_response_bytes_sum|\
          istio_tcp_received_bytes_total|\
          istio_tcp_sent_bytes_total|\
          process_resident_memory_bytes|\
          wasp(.*)|\
          workload(.*)|\
          last_metric"
        action: keep

      - source_labels: [job]
        regex: '(.*)'
        target_label: prometheus_job

      - regex: "\
          job"
        action: labeldrop
