---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-selfsigned
spec:
  commonName: demo.sandbox.wasp.silvios.me
  
  dnsNames:
    - demo.sandbox.wasp.silvios.me

  secretName: httpbin-selfsigned

  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
