---
apiVersion: v1
kind: Pod
metadata:
  name: mongoshell
  namespace: wasp
  labels:
    app: mongoshell
spec:
  restartPolicy: Never
  
  containers:
    - name: mongoshell
      image: docker.io/silviosilva/mongoshell:latest

      envFrom:
        - secretRef:
            name: mongoshell
