apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider:
    azurekv:
      authType:   ManagedIdentity
      tenantId:   "a267367d-d04d-4a6b-84ef-0cc227ed6e9f"
      identityId: "c13f3be6-b665-4743-aafa-77544cbfb5e8"
      vaultUrl:   "https://silvioswaspsandbox1.vault.azure.net"
