---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-selfsigned
spec:
  commonName: echo.example.com
  
  dnsNames:
    - echo.example.com

  secretName: httpbin-selfsigned

  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
