apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin

  ports:
    - name: http
      port: 8000
      targetPort: 80
