kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: test
  namespace: demo
spec:
  host: test.demo.svc.cluster.local
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
