apiVersion: v1
kind: Service
metadata:
  name: cert-manager-solver
  namespace: istio-system
  labels:
    app: cert-manager-solver
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8089
      protocol: TCP
      targetPort: http
  selector:
    acme.cert-manager.io/http01-solver: "true"
