---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-ingress-gateway
  namespace: {{ $.Values.istio.namespace }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ $.Values.istio.ingress.secret.name }}
      httpsRedirect: false
    hosts:
      - {{ $.Values.dns.prefix }}{{ $.Values.dns.domain }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-ingress-gateway-insecure
  namespace: {{ $.Values.istio.namespace }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ $.Values.dns.prefix }}{{ $.Values.dns.domain }}
    tls:
      httpsRedirect: false
