apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: istio-ingress-certificate
  namespace: istio-system
spec:
  secretName: {{ $.Values.istio.ingress.secret.name }}
  dnsNames:
    - {{ index .Values "dns" "prefix" }}{{ index .Values "dns" "domain" }}
  commonName: {{ index .Values "dns" "prefix" }}{{ index .Values "dns" "domain" }}
  issuerRef:
    name: {{ index .Values "issuer" "name" }}
    kind: Issuer
    group: cert-manager.io
