apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: certificate-ingress-traffic
  namespace: istio-system
spec:
  hosts:
  - {{ index .Values "dns" "prefix" }}{{ index .Values "dns" "domain" }}
  gateways:
  - public-insecure-ingress-gateway
  http:
  - match:
      - uri:
          prefix: /.well-known/acme-challenge/
    route:
      - destination:
          host: cert-manager-solver
