apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-cluster-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: wasp-foundation

  target:
    name: argocd-cluster-credentials

    creationPolicy: Owner
    
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      
      type: Opaque

      data:
        name: "{{ .name | toString }}"
        server: "{{ .host | toString }}"
        config: |
          {{ .credentialsConfig | toString }}

  data:
    - secretKey: "name"
      remoteRef:
        key: secret/aks-name

    - secretKey: "host"
      remoteRef:
        key: secret/aks-api-server-host

    - secretKey: "credentialsConfig"
      remoteRef:
        key: secret/aks-argocd-credentials-config
