---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  annotations:
    vault.hashicorp.com/role: "my-app"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-credentials.yaml: "secret/data/my-app/database"
    vault.hashicorp.com/agent-inject-template-credentials.yaml: |
      {{- with secret "secret/data/my-app/database" -}}
      connection:
        username: "{{ .Data.data.username }}"
        password: "{{ .Data.data.password }}"
      {{- end -}}
spec:
  serviceAccountName: app
  containers:
  - name: app
    image: silviosilva/utils
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 500; done"]
  restartPolicy: OnFailure
