apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-blue-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smsilva/argocd.git
    path: argo-rollouts/blue-green
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
