apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: pod.compositebuckets.silvios.me
spec:
  compositeTypeRef:
    apiVersion: silvios.me/v1alpha1
    kind: CompositeBucket
  resources:
    - name: terraform-azure-dummy-stack
      base:
        apiVersion: v1
        kind: Pod
        metadata:
          name: azure-dummy-stack
          namespace: default
        spec:
          containers:
            - name: terraform
              image: silviosilva/azure-dummy-stack:latest
              args: ["plan", "-no-color"]
              env:
                - name: DEBUG
                  value: "0"
              envFrom:
                - secretRef:
                    name: arm-credentials
          restartPolicy: OnFailure
