---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  ingressClassName: "nginx"
  
  rules:
    - host: ''
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8000

    - host: 'apps.example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin-node-port
                port:
                  number: 8080
