apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    install.istio.io/IstioOperator:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.status ~= nil then
            if obj.status.status == "HEALTHY" then
              hs.status = "Healthy"
              return hs
            end
            if obj.status.status == "RECONCILING" then
              hs.status = "Progressing"
              hs.message = "Operator is Reconciling"
              return hs
            end
          end
        end

        hs.status = "Unknown"
        return hs
