apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-cluster-credentials-wasp-na-sbx-a
  namespace: argocd
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster

  target:
    name: argocd-cluster-credentials-wasp-na-sbx-a

    creationPolicy: Owner
    
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      
      type: Opaque

      data:
        name: "{{ .name | toString }}"
        server: "{{ .host | toString }}"
        config: |
          {{ .credentialsConfig | toString }}

  data:
    - secretKey: "name"
      remoteRef:
        key: secret/cluster-name

    - secretKey: "host"
      remoteRef:
        key: secret/cluster-api-server-host

    - secretKey: "credentialsConfig"
      remoteRef:
        key: secret/cluster-api-server-credentials-argocd
