apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ntest
  name: ntest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ntest
  template:
    metadata:
      labels:
        app: ntest
    spec:
      containers:
      - image: nginx:1.19
        name: ntest
