apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - name: rule-1
    match:
    - uri:
        prefix: /api
    rewrite:
      uri: "/"
    route:
    - destination:
        host: nginx
        port:
          number: 80
  - name: rule-2
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx
        port:
          number: 80
