apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-org-dr
spec:
  host: httpbin-alias.default.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
      loadBalancer:
        simple: ROUND_ROBIN
