apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-ingress-routes
  namespace: demo
spec:
  hosts:
  - demo.example.com
  gateways:
  - public-ingress-gateway.istio-system.svc.cluster.local
  http:
  - route:
    - destination:
        host: httpbin.demo.svc.cluster.local
        port:
          number: 8000
