apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-ingress-routes
  namespace: demo
spec:
  hosts:
  - demo.example.com
  - httpbin.example.com
  - httpbin
  gateways:
  - public-ingress-gateway.istio-system.svc.cluster.local
  - mesh
  http:
    - name: httpbin
      headers:
        request:
          add:
            X-A1-custom: my-custom-value
      route:
      - destination:
          host: httpbin.demo.svc.cluster.local
          port:
            number: 8000
