apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: istio-system
spec:
  hosts:
  - {{ index .Values "dns" "prefix" }}{{ index .Values "dns" "domain" }}
  gateways:
  - ingress-gateway
  http:
  - route:
    - destination:
        host: httpbin.demo.svc.cluster.local
        port:
          number: 8000
