network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4-overrides:
        route-metric: 10
      nameservers:
        search: [${DOMAIN_NAME}]
        addresses: [${IP_DNS}, 8.8.8.8, 8.8.4.4]
