apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app
data:
  config-init.hcl: |
    auto_auth = {
      method = {
        config = {
          role = "my-app"
        }
        type = "kubernetes"      
      }

      sink = {
        config = {
          path = "/home/vault/.vault-token"
        }

        type = "file"
      }
    }

    exit_after_auth = true
    pid_file = "/home/vault/.pid"

    template = {
      destination = "/vault/secrets/credentials.yaml"
      contents = <<EOT
      {{- with secret "secret/data/my-app/database" -}}
      connection:
        username: "{{ .Data.data.username }}"
        password: "{{ .Data.data.password }}"
      {{- end -}}
      EOT
    }

    vault = {
      address = "http://vault.vault.svc:8200"
    }
