---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-configmap: "my-app"
    vault.hashicorp.com/agent-pre-populate-only: "true"
spec:
  serviceAccountName: my-app
  containers:
  - name: app
    image: silviosilva/utils
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 500; done"]
  restartPolicy: OnFailure
