spring:
  application:
    name: demo-health

server:
  port: 8080
  tomcat:
    max-threads: ${MAX_THREADS:500}

logging:
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}
  newRelic:
    appender:
      enabled: ${NEW_RELIC_APPENDER_ENABLED:false}
