---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-httpbin
spec:
  commonName: httpbin.example.com
  
  dnsNames:
    - httpbin.example.com

  secretName: ingress-httpbin-tls

  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
