service:
  # externalTrafficPolicy: Local

  type: NodePort

  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021

    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32080

    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 32443
