#cloud-config
hostname: ${SERVER_HOST_NAME}
fqdn: ${SERVER_HOST_NAME}.${DOMAIN_NAME}

packages:
 - bind9
 - bind9utils
 - bind9-doc
 - dnsutils

routes:
  - to: 10.96.0.0/16
    via: 127.0.0.1
    metric: 3
