---
- hosts: openstack
  name: OpenStack Objects Creation

  vars_files:
    - vars/openstack.yml

  tasks:

  - import_tasks: creation/ports.yml
  - import_tasks: creation/floating-ip.yml
  - import_tasks: creation/cloud-init.yml
  - import_tasks: creation/instances.yml
  
  - name: creates ansible inventory file
    template:
      src: inventory.ini.j2
      dest: inventory.ini

  - name: kubernetes nodes config
    shell: ansible-playbook -i inventory.ini ../kubernetes.yml
