---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-letsencrypt-staging
spec:
  commonName: echo.eks.sandbox.wasp.silvios.me
  
  dnsNames:
    - echo.eks.sandbox.wasp.silvios.me

  secretName: tls-letsencrypt-staging

  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging-nginx
