{{- range $service := .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: external
spec:
  type: ExternalName
  externalName: {{ $service.externalName }}
{{- end }}
