apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-gv0-pv-volume
  labels:
    type: gluster
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false
