# https://istio.io/latest/docs/ops/best-practices/observability/#using-prometheus-for-production-scale-monitoring
# https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation

- job_name: 'federate'
  scrape_interval: 15s

  honor_labels: true
  metrics_path: '/federate'

  params:
    'match[]':
      - '{job="kubernetes-pods"}'

  static_configs:
    - targets:
      - 'prometheus.istio-system:9090'

  metric_relabel_configs:
    - source_labels: [__name__]
      regex: "\
        ^envoy_(.*)|\
        ^istio_(.*)"
      action: keep

    - source_labels: [__name__]
      regex: '(.*)'
      replacement: 'federate:$1'
      target_label: __name__
      action: replace
