- job_name: 'kubernetes-coredns'
  honor_labels: true

  kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - kube-system
      selectors:
        - role: "pod"
          label: "k8s-app=kube-dns"

  relabel_configs:
    - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
      separator: '/'
      regex: 'kube-system/coredns.+'
      action: keep

    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)

    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)

    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      target_label: __address__
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2

    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)

    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace

    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: kubernetes_service_name

    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
