- job_name: 'kubernetes-state-metrics'
  honor_labels: true

  kubernetes_sd_configs:
    - role: pod

  relabel_configs:
    - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
      separator: '/'
      regex: 'prometheus/.*kube-state-metrics.*'
      action: keep

    - source_labels:
        - __meta_kubernetes_pod_name
      target_label: instance
      action: replace

    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
