- job_name: 'kubernetes-node-exporter'
  honor_labels: true

  kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - prometheus

  relabel_configs:
    - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
      separator: '/'
      regex: 'prometheus/.*node-exporter.*'
      action: keep

    - source_labels:
        - __meta_kubernetes_pod_name
      target_label: instance
      action: replace

    - source_labels: [__meta_kubernetes_pod_node_name]
      action: replace
      target_label: node

    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
