- job_name: 'kubernetes-services'
  honor_labels: true

  kubernetes_sd_configs:
    - role: service

  relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_prometheus_io_scrape]
      action: keep
      regex: true

    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: namespace

    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: service
