---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 6

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      nodeSelector:
        disktype: ssd

      initContainers:
        - name: sleep
          image: busybox
          command:
            - sh
            - -c
            - sleep 10

      containers:
        - image: nginx:latest
          name: nginx
