---
apiVersion: v1
kind: Pod
metadata:
  name: mongoshell
  labels:
    app: mongoshell
    shell: "true"
spec:
  nodeName: "${NODE_NAME}"
  restartPolicy: Never
  hostPID: true
  hostNetwork: true
  dnsPolicy: Default
 
  containers:
    - name: mongoshell
      image: docker.io/silviosilva/mongoshell:latest

      envFrom:
        - secretRef:
            name: mongoshell

      command:
        - sleep
        - infinity

    - name: nsenter
      image: mcr.microsoft.com/dotnet/runtime-deps:6.0
      stdin: true
      stdinOnce: true
      tty: true

      securityContext:
        privileged: true
        capabilities:
          add: [ "NET_ADMIN" ] # SYS_PTRACE replaced by NET_ADMIN

      command: [ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash", "-l" ]
