---
apiVersion: v1
kind: Pod
metadata:
  name: mongoshell
  namespace: wasp
  labels:
    app: mongoshell
spec:
  nodeName: "kind-control-plane"
  restartPolicy: Never
  hostPID: true
  hostNetwork: true
  dnsPolicy: Default

  volumes:
    - name: shared-data
      hostPath:
        path: /files
        type: Directory
 
  containers:
    - name: mongoshell
      image: docker.io/silviosilva/mongoshell:latest

      envFrom:
        - secretRef:
            name: mongoshell

      volumeMounts:
        - name: shared-data
          mountPath: /files

      command:
        - sleep
        - infinity

    - name: nsenter
      image: mcr.microsoft.com/dotnet/runtime-deps:6.0
      stdin: true
      stdinOnce: true
      tty: true

      volumeMounts:
        - name: shared-data
          mountPath: /files

      securityContext:
        privileged: true
        capabilities:
          add: [ "NET_ADMIN" ] # SYS_PTRACE replaced by NET_ADMIN

      command: [ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash", "-l" ]
